[application]
private_key = "7be42b204c00d965c891848c06180f504dbf0e26f8bbae647d8bf366dacea17a"
ping_interval = 60

[server]
bind = "[::1]:3001"

[grpc]
bind = "[::1]:50001"

[network]
connect_to = [
    
]

